name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish Draft PDF
    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          documento.tex
          apresentacao.tex
    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: draft_tcc
        path: |
          documento.pdf
          apresentacao.pdf
