name: publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish PDF
    runs-on: ubuntu-latest

    steps:
    - uses: xu-cheng/latex-action@v2
    - name: Build
      run: make build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: documento.pdf
        asset_name: tcc_manoel_vilela_${{ github.ref }}.pdf
        tag: ${{ github.ref }}
        overwrite: true
        body: "TCC Autogerado via CI/CD"
