name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish PDF
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: xu-cheng/latex-action@v2
      with:
        root_file: documento.tex
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: documento.pdf
        asset_name: tcc_manoel_vilela_${{ github.ref_name }}.pdf
        tag: ${{ github.ref }}
        overwrite: true
        body: "TCC Autogerado via CI/CD"
