# Add to: .github/workflows/spell-check.yml
name: spell-check

on:
  push:
    branches-ignore:
      - master

jobs:
  spellcheck:
    name: typocheck
    runs-on: ubuntu-latest
    timeout-minutes: 4
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: TypoCheck
      uses: typoci/spellcheck-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
